# Generated by Django 3.2.5 on 2024-05-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtube', '0009_alter_userhistory_vid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='channelPic',
            field=models.ImageField(default='', max_length=200, upload_to='public/videos/thumbnail'),
        ),
    ]
